### ISSUE TITLE
Generate control totals data

### ISSUE THREAD

**Issue by KyTriNguyenMonash** [KyTriNguyenMonash/achilles#4]
The control totals file is the marginal distributions that constrains the population synthesis procedure. In other words, PopulationSim has to make sure its synthetic population match with the total numbers that are specified in `control_totals.csv`.
The main task of PopulationSim is to create the right number of households and persons in each geographic zones. So, make sure to specify a control on total number of households and persons in each geographical zone at the lowest geographical level. 
For example, if you want to generate your synthetic population in SA2 level, your control total should be at least at SA2 or lower.

## Tasks:

- [ ] Create a control total file that consists of: Total population, Total households, information for each attributes that appeared in seed files for each zonal area.
- [ ] Validate control total data with persons and households seed. Make sure that your control total is in the lowest geographical level. (SA2)
- [ ] Create the driver script that will invoke this process using cmd arguments supplied by the user.

After this task, you have pretty much all of the required input for PopulationSim. The next step is to understand the configuration and file system of PopulationSim before having a complete run.

**Comment by bobkatla** [comment]
I have partly finished this task (will make change to to driver script later), it can be found on the branch "Test total" (including the created totals)

**Comment by bobkatla** [comment]
Here are the data: https://drive.google.com/drive/folders/16-MSqeFtMXx843kdyICShRKSMSDlWKLQ
